# Generated by Django 4.0.1 on 2022-02-07 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0002_recreate_game_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gameraterapi.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameimage',
            name='base64',
            field=models.TextField(default='base64data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamereview',
            name='date_time',
            field=models.DateTimeField(default='2022-02-06 01:51:46.497111'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gameraterapi.game'),
        ),
        migrations.AlterField(
            model_name='gameimage',
            name='image',
            field=models.ImageField(null=True, upload_to='gameimages'),
        ),
        migrations.AlterField(
            model_name='gamerating',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='gameraterapi.game'),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gameraterapi.game'),
        ),
        migrations.AlterField(
            model_name='gamereview',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='gameraterapi.player'),
        ),
    ]
